### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by jonchon** [CS130-W20/team-A8#10]
As a user, I would like to have my own profile page so that other people can see my profile and figure out whether I am someone they would like to play games with.

**Comment by jasche7** [comment]
All users have a profile page that contains user information, hosted games, and favorite games. The information can be edited if the profile page belongs to the user. Otherwise, certain information will be hidden unless the user chooses to share additional information with another user.

**Comment by jasche7** [comment]
Final commit:
cf93020a22dbb8a5f5436fbdd3af31ecab01f8b0
