### ISSUE TITLE
Home Page 

### ISSUE THREAD

**Issue by tiffanychandra** [CS130-W20/team-A8#15]
Frontend story - Home Page currently holds only facebook login button and will try to match Mockup on Figma with backdrop and text styles.

After the login success, should redirect to the profile or landing page.

**Comment by jasche7** [comment]
Home page currently has a Facebook login button that prompts actual Facebook login, but will be changed later on to use our backend.

The header links to other pages.

**Comment by jasche7** [comment]
Home page now correctly allows Facebook log in and then redirects to profile page. First time users will be prompted to add profile information.

**Comment by jasche7** [comment]
Final commit:
#5d1bb0d6407f2bc87c233d856a56e196d8acb67d
