### ISSUE TITLE
Navigation/Log in Access

### ISSUE THREAD

**Issue by tiffanychandra** [CS130-W20/team-A8#16]
Currently, as a user I am able to navigate to all the pages without login access and see games, hosts, etc. 
I should not be able to access the profile without logging in first. I should see a pop up login notification in order to access certain pages on the application.

**Comment by jasche7** [comment]
Profile functionality is completely done. Viewing profiles, searching profiles, and editing profile information are all functional.

**Comment by jasche7** [comment]
Final commit:
d82d3d4399fd57cab9b18c7bc7fa2734364a3d79
