### ISSUE TITLE
Accept User Connection

### ISSUE THREAD

**Issue by willtan510** [CS130-W20/team-A8#3]
## User Story
As a Host, I would like to be able to accept/reject pending connections so that I can match with a user who wishes to connect.

**Comment by jasche7** [comment]
We ended up abandoning the connections concept and users can freely interact with each other as long as they can find each other. Some profile information will be hidden unless they choose to share additional information, however.

**Comment by jasche7** [comment]
Final commit:
d82d3d4399fd57cab9b18c7bc7fa2734364a3d79
