### ISSUE TITLE
Update profile page

### ISSUE THREAD

**Issue by willtan510** [CS130-W20/team-A8#4]
## User Story
As a User, I would like customize/update my profile page so that other users have information to judge whether they should connect/match.

**Comment by jasche7** [comment]
The profile page information, including avatar, can be updated it if belongs to the current user. However, the avatar will not update unless the page is reloaded.

**Comment by jasche7** [comment]
Final commit: 
6953d94d6852eda4991b5f65c64498da4d125e34
