### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by jonchon** [CS130-W20/team-A8#9]
As a user, I would like to be able to send messages so that I can contact another user and set up a game meetup.

**Comment by jasche7** [comment]
The messages page has been created, as well as the api for handling messaging. We must first develop the login system to proceed.

**Comment by julienmcollins** [comment]
A user can message another user from either their profile page, or if they're already in contact, from their inbox. If messaged from their profile directly, puts them in contact for future communication and opens a messaging modal automatically

**Comment by julienmcollins** [comment]
See commits:

4206316e50667961ad73e766b6d0298fa6306fcc
8345248cf2fc3d5c09fff446694b91e814e9b5d6
690e402345d7109d89a0338a89e22aded4a1c605
